apiVersion: v1
kind: Namespace
metadata:
  name: int
  labels:
    environment: int
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: int-quota
  namespace: int
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: "10"
